# Generated by Django 5.0.4 on 2024-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="abbreviation",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="team",
            name="mascot",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="team",
            name="nickname",
            field=models.CharField(max_length=30),
        ),
    ]
