"""
Django settings for cfbpicker project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path


# helper functions for determining boolean env variables. Sometimes different run environments can cause issues,
#  but this pretty much solves that
def default_false(env_var: str):
    """Default to False and see if an environment variable toggles something on"""
    return os.getenv(env_var, False) in (True, "true", "True", 1, "1")


def default_truth(env_var: str):
    """Default to True and see if an environment variable toggles something off"""
    return os.getenv(env_var, True) in (False, "false", "False", 0, "0")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&6(t3hb1q&9#b8fu-t*xtgsa$q30+*#)-xhi-rs$d8ft7!o50r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = default_false("DEBUG")

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "teams.apps.TeamsConfig",
    "games.apps.GamesConfig",
    "accounts.apps.AccountsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cfbpicker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cfbpicker.wsgi.application"


# Database is either expected to "be there" for local dev and production, but CI needs to instantiate one
#  This if statement boots up a Postgres container while loading settings, meant to be in a CI env like Github Actions
if default_false("IS_CI"):
    # import locally as it's not guaranteed to be part of the dependencies
    #  only in dev-dependencies
    from testcontainers.postgres import PostgresContainer

    postgres_container = PostgresContainer()
    postgres_container.start()

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': postgres_container.dbname,
            'USER': postgres_container.username,
            'PASSWORD': postgres_container.password,
            'HOST': postgres_container.get_container_host_ip(),
            'PORT': postgres_container.get_exposed_port(postgres_container.port),
        }
    }
else:
    # These defaults are for the local test environment. Production is expected to override most of these
    DB_USER = os.getenv("DB_USER", "postgres")
    DB_PASS_FILE = os.getenv("DB_PASS_FILE", "db/password.txt")
    DB_HOST = os.getenv("DB_HOST", "localhost")
    DB_PORT = os.getenv("DB_PORT", 5432)
    if DB_USER is None or DB_PASS_FILE is None or DB_HOST is None or DB_PORT is None:
        raise EnvironmentError("Database information was not properly supplied")
    with open(DB_PASS_FILE) as pass_file:
        password = pass_file.read()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'cfbpicker',
            'USER': DB_USER,
            'PASSWORD': password,
            'HOST': DB_HOST,  # Service name of the PostgreSQL container in Docker Compose
            'PORT': DB_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/accounts/account_login/"
