services:
  api:
    build: .
    secrets:
      - db-password
      - django-secret-key
    ports:
      - "8000:8000"
    env_file:
      - .envs/fake-production.env
    entrypoint: /app/entrypoint.sh
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  postgres:
   image: postgres
   restart: always
   user: postgres
   secrets:
     - db-password
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: postgres
     POSTGRES_DB: cfbpicker
     POSTGRES_PASSWORD_FILE: /run/secrets/db-password
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
volumes:
 db-data:
   name: fake-prod-cfb-picker-db-data
secrets:
 db-password:
   file: db/prod-db-password.txt
 django-secret-key:
   file: db/django-secret-key.txt

