# Generated by Django 5.0.4 on 2024-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="kickoff",
            field=models.DateTimeField(null=True),
        ),
    ]
