# Generated by Django 5.0.4 on 2024-04-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gameprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="location",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="gameprediction",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="predictions",
                to="games.game",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameprediction",
            unique_together={("user", "game")},
        ),
    ]
